eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

server:
  port: 8070
spring:
  application:
    name: coach
  config:
    import: optional:configserver:http://localhost:8888
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USERNAME} # postgres
    password: ${DB_PASSWORD} # root
    schema: coach
  flyway:
    locations: classpath:db/migration
    schemas: coach
    enabled: true
    baselineOnMigrate: true
    cleanDisabled: false
    cleanOnValidationError: true
    clean-on-startup: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  config:
    members-url: http://localhost:8222/api/v1/stats
